"""
Quality Check agent for narrated PPTX.

For each slide that has embedded audio:
  1. Extract the MP3 from the PPTX zip.
  2. Transcribe it via Azure STT.
  3. Ask GPT-5.2 to compare the original script text with the transcription
     and return a structured confidence score + issues list.

Uses DefaultAzureCredential — no API key required.
Azure OpenAI endpoint: https://bhs-development-public-foundry-r.cognitiveservices.azure.com
Deployment: gpt-5.2
"""
import json
import zipfile
import os
import httpx
from azure.identity import DefaultAzureCredential

from stt_client import transcribe_mp3
from translator import _locale_from_voice

COGNITIVE_SERVICES_SCOPE = "https://cognitiveservices.azure.com/.default"

_OPENAI_ENDPOINT = os.environ.get(
    "AZURE_OPENAI_ENDPOINT",
    "https://bhs-development-public-foundry-r.cognitiveservices.azure.com",
).rstrip("/")
_OPENAI_DEPLOYMENT = os.environ.get("AZURE_OPENAI_DEPLOYMENT", "gpt-5.2")
_OPENAI_API_VERSION = "2024-12-01-preview"

_CHAT_URL = (
    f"{_OPENAI_ENDPOINT}/openai/deployments/{_OPENAI_DEPLOYMENT}"
    f"/chat/completions?api-version={_OPENAI_API_VERSION}"
)

_SYSTEM_PROMPT = """You are an audio quality evaluation assistant.
You will be given the ORIGINAL script text that was intended to be spoken,
and a TRANSCRIPTION of the actual audio that was generated by a text-to-speech system.

Your task is to compare the two and evaluate the accuracy of the TTS output.

Respond ONLY with a JSON object in this exact schema — no markdown, no explanation:
{
  "confidence": <integer 0-100>,
  "issues": [<string>, ...],
  "summary": "<one sentence>"
}

confidence: 100 = perfect match, 0 = completely different.
issues: list specific word substitutions, omissions, or additions. Empty array if none.
summary: concise one-sentence verdict.

If the original was in English but the transcription is in a different language
(because translation was applied before TTS), evaluate the transcription for
fluency and completeness relative to the translated content, not the English original."""


def _score_slide(original_text: str, transcription: str) -> dict:
    """Call GPT-5.2 to compare original vs transcription and return a score dict."""
    if not transcription.strip():
        return {
            "confidence": 0,
            "issues": ["No audio transcription returned — audio may be silent or STT failed"],
            "summary": "Unable to evaluate: no transcription available",
        }

    aad_token = DefaultAzureCredential().get_token(COGNITIVE_SERVICES_SCOPE).token

    payload = {
        "messages": [
            {"role": "system", "content": _SYSTEM_PROMPT},
            {
                "role": "user",
                "content": (
                    f"ORIGINAL SCRIPT:\n{original_text}\n\n"
                    f"AUDIO TRANSCRIPTION:\n{transcription}"
                ),
            },
        ],
        "temperature": 0,
        "max_tokens": 300,
        "response_format": {"type": "json_object"},
    }

    print(f"[QA] Calling GPT-5.2 to score slide...", flush=True)
    response = httpx.post(
        _CHAT_URL,
        headers={
            "Authorization": f"Bearer {aad_token}",
            "Content-Type": "application/json",
        },
        content=json.dumps(payload),
        timeout=60,
    )
    response.raise_for_status()

    content = response.json()["choices"][0]["message"]["content"]
    result = json.loads(content)
    print(f"[QA] Score={result.get('confidence')}  issues={len(result.get('issues', []))}", flush=True)
    return result


def run_quality_check(
    pptx_bytes: bytes,
    slide_texts: list[dict],   # [{"title": str, "text": str}, ...] from word_parser
    voice: str,                # e.g. "fr-FR-DeniseNeural" — used to derive STT locale
) -> list[dict]:
    """
    Returns a list of per-slide quality results, one entry per slide that has audio.
    Slides without audio get confidence=None.
    """
    locale = _locale_from_voice(voice)

    # Extract all MP3 files from the PPTX zip
    audio_map: dict[int, bytes] = {}  # 1-based slide index → mp3 bytes
    with zipfile.ZipFile(pptx_bytes if not isinstance(pptx_bytes, bytes)
                         else __import__('io').BytesIO(pptx_bytes)) as z:
        for name in z.namelist():
            # Files are named audio_slide{N}.mp3
            if name.startswith("ppt/media/audio_slide") and name.endswith(".mp3"):
                try:
                    n = int(name.split("audio_slide")[1].replace(".mp3", ""))
                    audio_map[n] = z.read(name)
                except ValueError:
                    pass

    results = []
    for slide_idx, slide in enumerate(slide_texts):
        slide_num = slide_idx + 1  # 1-based

        if slide_num not in audio_map:
            results.append({
                "slide": slide_num,
                "title": slide.get("title", f"Slide {slide_num}"),
                "original_text": slide.get("text", ""),
                "transcription": None,
                "confidence": None,
                "issues": [],
                "summary": "No audio embedded for this slide",
            })
            continue

        print(f"[QA] Slide {slide_num}: transcribing audio...", flush=True)
        transcription = transcribe_mp3(audio_map[slide_num], locale=locale)

        score = _score_slide(slide.get("text", ""), transcription)

        results.append({
            "slide": slide_num,
            "title": slide.get("title", f"Slide {slide_num}"),
            "original_text": slide.get("text", ""),
            "transcription": transcription,
            "confidence": score.get("confidence"),
            "issues": score.get("issues", []),
            "summary": score.get("summary", ""),
        })

    return results
